### PR TITLE
DOC-4728: Updated 4.10 Upgrading CorDapps to newer Platform Versions

### PR DESCRIPTION
**Pull request by AnnaK-R3**

### CODE REVIEW

**Review by paulmoloneyr3 — DISMISSED** [review]

**Review by yarivus — APPROVED** [review]
LGTM

**Review by adelel1 — COMMENTED** [review]
Not clear to me why this upgrade information is now being deleted. 
This change now assumes everyone is currently at version 4.7 or higher.
If some one is at a lower version and they want to upgrade we've now deleted the info for them.

**Review by yarivus — APPROVED** [review]
LGTM-clean merge

**Comment by AnnaK-R3** [comment]
> Not clear to me why this upgrade information is now being deleted. This change now assumes everyone is currently at version 4.7 or higher. If some one is at a lower version and they want to upgrade we've now deleted the info for them.

**Review by nadinequinr3 — APPROVED** [review]
LGTM

**Pull request merged**
