### PR TITLE
FE-73: Fix breadcrumb's position 

### PR DESCRIPTION
**Pull request by zhengmar3**
### Overview

JIRA: https://r3-cev.atlassian.net/browse/FE-73

Breadcrumb is now fixed at the top of pages so that it’s always visible, regardless of user scrolling.

Screenshot 2023-04-05 at 11 51 29

However, the original position/layout is kept for smaller screen (e.g. on mobile deviceS), meaning it will get hidden once user scroll further down the page. Since we got very limited display on small device, it's best practice and common to not to fix non-essential ui element on the screen.
Screenshot 2023-04-05 at 14 16 18

### CODE REVIEW

**Comment by nadinequinr3** [comment]
Thanks, @zhengmar3. There's a preview site here: https://docs.preview.docs.r3.com/en/platform/corda/5.0-beta.html
There's an issue when you click one of the top drop-down menus from a page with a breadcrumb:
image
Also, do you think some kind of border or something under the breadcrumb to differentiate it from the main content would be nice?

**Review by nadinequinr3 — APPROVED** [review]
LGTM

**Review by yarivus — COMMENTED** [review]
thx @zhengmar3

**Comment by Skylerspencer** [comment]
Really

**Pull request merged**
