### PR TITLE
FE-85: Breacrumb background bug when on dark mode.

### PR DESCRIPTION
**Pull request by zhengmar3**
### Overview

JIRA: https://r3-cev.atlassian.net/browse/FE-85

When we fixed the position of the breadcrumb, the background color has to be set so that the content below scrolls through can be hidden.  But when the site is in dark mode, the background color needs to change to match the dark theme. See the screenshot for the bug:
image

### Solution
So I added the styling for the dark theme background.
Screenshot of the breadcrumb after the fix:
image

### CODE REVIEW

**Comment by nadinequinr3** [comment]
Built a preview [here](https://paul.preview.docs.r3.com/) and looks good.
Good spot @zhengmar3. Thanks

**Review by nadinequinr3 — APPROVED** [review]

**Review by conor-r3 — APPROVED** [review]

**Comment by conor-r3** [comment]
It looks like this change might be needed to be added to table rows as well. I can create a ticket.
Screenshot 2023-04-25 at 13 11 50

**Comment by zhengmar3** [comment]
> It looks like this change might be needed to be added to table rows as well. I can create a ticket. Screenshot 2023-04-25 at 13 11 50

I can create one.
Would expect to find more issue like this I think in other pages...Will look into it.

**Comment by nadinequinr3** [comment]
> > It looks like this change might be needed to be added to table rows as well. I can create a ticket. Screenshot 2023-04-25 at 13 11 50
> 
> I can create one. Would expect to find more issue like this I think in other pages...Will look into it.

Thanks @conor-r3 and @zhengmar3!
I will merge and publish this fix now.

**Review by yarivus — COMMENTED** [review]
thx @zhengmar3

**Pull request merged**
