### PR TITLE
FE-72: Fix lefthand menu with separate scrollbar. 

### PR DESCRIPTION
**Pull request by zhengmar3**
### Overview

**JIRA**: https://r3-cev.atlassian.net/browse/FE-72

**Issue**: left hand index menu in docs should not scroll up and down in sync with the main content window. When the doc page is long, as the user scrolls, eventually the left hand index menu can no longer be seen at all.

**Fix**: There should be a separate scroll window for the left menu, so that when several items are expanded, the user can scroll the menu independently of the the main content window.

### Screenshot
image

### CODE REVIEW

**Comment by nadinequinr3** [comment]
Hi @zhengmar3, I published a preview of this PR [here ](https://nadine.preview.docs.r3.com/) for review.

Something funny seems to be happening with the footer when you scroll to the bottom. It's especially strange on pages where the left-hand menu is long. For example: https://nadine.preview.docs.r3.com/en/platform/corda/5.0-beta/developing/development-tutorials/build-basic-cordapp/basic-cordapp-state.html
image

**Comment by zhengmar3** [comment]
> **Fix**: There should be a separate scroll window for the left menu, so that when several items are expanded, the user can scroll the menu independently of the the main content window.

@nadinequinr3 

Ok, let me try to fix it. Could be very tricky to fix due to hugo while keep the left-band bar fixed on its position.

**Comment by zhengmar3** [comment]
@nadinequinr3 
You can have a look.
I sort of have a fix for this, although it's not perfect. Cos for most docs site with table of content on the left-side, it seems to not having big footer like ours.


image

**Comment by nadinequinr3** [comment]
> @nadinequinr3 You can have a look. I sort of have a fix for this, although it's not perfect. Cos for most docs site with table of content on the left-side, it seems to not having big footer like ours.
> 
> image

Thanks @zhengmar3. It's definitely better than it was. @colin-hillis can you take a look to see if you're happy?

**Pull request merged**
