### PR TITLE
OS-archive-4.5-4.8

### PR DESCRIPTION
**Pull request by colin-hillis**
Removal of OS 4.5-4.8 files to the archiving folder.  
Update of both indexes to reflect reduced versions.  
Updated menu.toml file to reflect archived versions.

### CODE REVIEW

**Comment by nadinequinr3** [comment]
Should the "open source" link on https://docs.r3.com/en/release-notes.html be removed?

**Review by yarivus — DISMISSED** [review]
LGTM

**Comment by colin-hillis** [comment]
Also a remaining instance of Corda OS was changed to Corda Community.

**Review by nadinequinr3 — DISMISSED** [review]
LGTM

**Pull request merged**
