### PR TITLE
Doc 4495: Added new section labelled Corda CLI Reference

### PR DESCRIPTION
**Pull request by Niamh25**
New section added to beta labelled Corda CLI reference, CLI command content moved to this section. Use Case section has been moved to drafts.

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Review by nadinequinr3 — CHANGES_REQUESTED** [review]
I think the [cli-commands.md](https://github.com/corda/corda-docs-portal/pull/850/files#diff-903de7bee51f874561974e128d0ac3a93d62fda2b0eb581fff763f8d9dd7192b) file should be renamed to package and moved to the cli-commands folder. The name of that page should also be changed to "package" for consistency

image

**Comment by nadinequinr3** [comment]
Just another thought, have you checked links to the files that you moved? For example, there's a link from the packaging tutorial to the packaging commands reference.

**Review by nadinequinr3 — DISMISSED** [review]

**Review by yarivus — COMMENTED** [review]
thx @Niamh25 & @nadinequinr3

**Pull request merged**
