### PR TITLE
FE-52: Update nav bar so that scrolled text can not be seen

### PR DESCRIPTION
**Pull request by zhengmar3**
### Overview

Jira: https://r3-cev.atlassian.net/jira/software/c/projects/FE/boards/867?modal=detail&selectedIssue=FE-52 

Changed the opacity of the background image of navbar of the site header to 1. So that scrolled text can not be seen.

See screenshot:
Screenshot 2023-02-15 at 16 57 19

### CODE REVIEW

**Review by colin-hillis — APPROVED** [review]
LGTM

**Comment by nadinequinr3** [comment]
Will this resolve the issue with heading links not displaying at the correct point?

**Comment by zhengmar3** [comment]
> Will this resolve the issue with heading links not displaying at the correct point?

@nadinequinr3 

What do you mean by "heading links not displaying at the correct point"?

But this is a very minor CSS style change, all I did is: change the opacity of the navbar background to NOT be transparent, so when text scrolled up not seen.

It will not solve any other ui/ux issue.

**Comment by nadinequinr3** [comment]
Thanks, @zhengmar3.
There is an issue on the docs site when a user clicks a link to a specific section; the top of the page displayed is hidden under the header and so the user is brought to a point further in the text, than expected. For example, https://docs.r3.com/en/platform/corda/5.0-beta/introduction/key-concepts.html#flows - the user would expect to see the "Flows" heading at the top of the page.
@colin-hillis do we have another ticket for the FE team to resolve this?

**Comment by zhengmar3** [comment]
> Thanks, @zhengmar3. There is an issue on the docs site when a user clicks a link to a specific section; the top of the page displayed is hidden under the header and so the user is brought to a point further in the text, than expected. For example, https://docs.r3.com/en/platform/corda/5.0-beta/introduction/key-concepts.html#flows - the user would expect to see the "Flows" heading at the top of the page. @colin-hillis do we have another ticket for the FE team to resolve this?

@nadinequinr3 @colin-hillis 
Right, I see what you mean.
Yes, there is separate ticket created for this issue:
https://r3-cev.atlassian.net/browse/FE-48

**Comment by nadinequinr3** [comment]
> > Thanks, @zhengmar3. There is an issue on the docs site when a user clicks a link to a specific section; the top of the page displayed is hidden under the header and so the user is brought to a point further in the text, than expected. For example, https://docs.r3.com/en/platform/corda/5.0-beta/introduction/key-concepts.html#flows - the user would expect to see the "Flows" heading at the top of the page. @colin-hillis do we have another ticket for the FE team to resolve this?
> 
> @nadinequinr3 @colin-hillis Right, I see what you mean. Yes, there is separate ticket created for this issue: https://r3-cev.atlassian.net/browse/FE-48

Oh great. Apologies, I thought they were being treated as one fix. Thanks!

**Comment by zhengmar3** [comment]
btw, I don't have the permission to merge PR.
Therefore someone please merge this PR for me hah.
@nadinequinr3 @colin-hillis

**Comment by nadinequinr3** [comment]
> btw, I don't have the permission to merge PR. Therefore someone please merge this PR for me hah. @nadinequinr3 @colin-hillis

Done. Thanks @zhengmar3

**Pull request merged**
