### PR TITLE
Niamh25/doc 5498/table of certificates

### PR DESCRIPTION
**Pull request by Niamh25**
Created a table for the list of supported key certificates and certificates. Content subject to change currently.

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Review by yarivus — APPROVED** [review]
LGTM

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by nadinequinr3** [comment]
Closing PR to create a new one based on the latest main branch.

**Pull request closed without merging**
