### PR TITLE
add new pages shortcode

### PR DESCRIPTION
**Pull request by nadinequinr3**
add a shortcode that will display cross-references to all child pages, sorted by their weight in the corda5 menu

### CODE REVIEW

**Comment by yarivus** [comment]
can you provide a screenshot ?

**Comment by nadinequinr3** [comment]
> can you provide a screenshot ?

Running locally:

image
image

**Comment by yarivus** [comment]
> > can you provide a screenshot ?
> 
> Running locally:
> 
> image image

Thanks @nadinequinr3 
So instead of the commented out (green) explicit specification of the child pages and links - you just use `{{pages}}` ?
If so shouldn't it be renamed to `{{childpages}}` ?

**Comment by nadinequinr3** [comment]
> > > can you provide a screenshot ?
> > 
> > 
> > Running locally:
> > image image
> 
> Thanks @nadinequinr3 So instead of the commented out (green) explicit specification of the child pages and links - you just use `{{pages}}` ? If so shouldn't it be renamed to `{{childpages}}` ?

Exactly!
Sure - I'll rename. I was probably swayed by the (not always helpful) Hugo terminology.

**Comment by yarivus** [comment]
Nice one @nadinequinr3  😉

**Review by yarivus — APPROVED** [review]
LGTM

**Review by yarivus — APPROVED** [review]
LGTM

**Pull request merged**
