### PR TITLE
Niamh25/doc 5199/provide default digest algorithm and supported digest algorithms ap is

### PR DESCRIPTION
**Pull request by Niamh25**
Added new API Digest Service to Crypto API list.

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by Niamh25** [comment]
Kyriakos suggested that it may be better to change this section to bullet points, should we?

**Review by paulmoloneyr3 — APPROVED** [review]

**Comment by paulmoloneyr3** [comment]
> 

Yep I think so too.

**Review by colin-hillis — APPROVED** [review]
LGTM

**Pull request merged**
