### PR TITLE
DOC-3776 Patch release: log4j v2.17.1 docs update Part I

### PR DESCRIPTION
**Pull request by michelemarsden**
* DOC-3791 Added legal info for CE 4.4.11

* DOC-3788 Added legal info for CE 4.5.9

* DOC-3785 Added legal info for CE 4.6.8

* DOC-3782 Added legal info for CE 4.7.6

### CODE REVIEW

**Review by taylorharvey-r3 — APPROVED** [review]
LGTM

**Review by taylorharvey-r3 — APPROVED** [review]
LGTM

**Review by nargas-ritu — APPROVED** [review]
LGTM

**Comment by michelemarsden** [comment]
Sachin reviewed and approved preview site.

**Pull request merged**
