### PR TITLE
EG-937 - DOS attack vulnerability for identity manager

### PR DESCRIPTION
**Pull request by nikinagy**
Added new section about discovered vulnerability for Identity Manager.
https://r3-cev.atlassian.net/browse/EG-937

### CODE REVIEW

**Review by benpesterr3 — CHANGES_REQUESTED** [review]
If possible, we need to offer steps that the user can take to negate this threat.

**Comment by nikinagy** [comment]
I am afraid there are no steps to avoid this problem without any code fix on cenm side.

**Comment by colin-hillis** [comment]
> LGTM

There are open questions about this PR, especially around whether it should be included or not. Awaiting answers from CENM team and once any changes are made, then Technical Writing will review.

**Comment by colin-hillis** [comment]
This PR will be archived or deleted, as there is no longer an appetite to serve this to customers.

**Pull request closed without merging**
