### PR TITLE
DOC-322 Removed references to READ_COMMITTED

### PR DESCRIPTION
**Pull request by michelemarsden**
References to READ_COMMITED config deleted as no longer actual. Some had already been deleted. Awaiting outcome of PR 413 to see if it should also be removed from ENT 4.5.

### CODE REVIEW

**Review by blsemo — APPROVED** [review]
LGTM

**Comment by michelemarsden** [comment]
Changes not required in ENT 4.5.

**Review by taylorharvey-r3 — APPROVED** [review]
LGTM

**Review by AaronForinton — APPROVED** [review]
LGTM

**Pull request merged**
