### PR TITLE
Fe 48 table of content alignment issue

### PR DESCRIPTION
**Pull request by zhengmar3**
### Overview

**Front-end Jira ticket:** 
https://r3-cev.atlassian.net/browse/FE-48

**The issue:** 
"At the moment, when you click on an item from the Contents section in the right-hand pane, the correct section appears at the top of the page but its title is covered by the top grey panel so it may appear like you’re somewhere else. "

**Solution:**
Added `scroll-margin-top: 155px; ` to all header element to offset the fixed height of the appbar.

**Note:**
This does not fix the existing issue: the table of contents on the right side does not highlight the active sections correctly. And when user click on individual header, often wrong or confusing header got highlighted instead.
I have created a new jira ticket to track work on this:
https://r3-cev.atlassian.net/browse/FE-63

### CODE REVIEW

**Review by colin-hillis — APPROVED** [review]
LGTM - thanks Zheng

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by zhengmar3** [comment]
@nadinequinr3 Could you review and if it's all good, then merge the PR for me.

**Comment by nadinequinr3** [comment]
> @nadinequinr3 Could you review and if it's all good, then merge the PR for me.
@zhengmar3 Looks better already, thanks!

**Pull request merged**
