### PR TITLE
DOC-4372 Add OpenShift support

### PR DESCRIPTION
**Pull request by davidcurrie**

### CODE REVIEW

**Review by yarivus — COMMENTED** [review]
Looks good so far ;)

**Comment by nadinequinr3** [comment]
I rewrote the content into steps.
Leaving as draft for now for @milan-khan to confirm version number, as per @davidcurrie. Thanks.

**Review by yarivus — COMMENTED** [review]
Thanks @nadinequinr3 - steps is much better ;)

**Comment by davidcurrie** [comment]
We didn't get a satisfactory answer from the customer (they gave a version that is out of support) so I propose we continue with 4.10 and I'll switch this PR to "Ready for review".

**Review by yarivus — APPROVED** [review]
LGTM

**Review by nadinequinr3 — APPROVED** [review]

**Pull request merged**
