### PR TITLE
FE-91: Added tooltip to sidebar link content.

### PR DESCRIPTION
**Pull request by zhengmar3**
JIRA: https://r3-cev.atlassian.net/browse/FE-91

The simple fix would be to add a tooltip to the truncated context of the sidebar menu.

The option to make the sidebar resizeable can be tricky due to how the base layout of the doc site setup. Also by doing that, we might need to fix any potential bugs introduced by the resizeable sidebar to other UI elements.

Overall tooltip for now is a better fix at the moment.

image

### CODE REVIEW

**Comment by nadinequinr3** [comment]
Preview here: https://docs.staging.docs.r3.com/en/platform/corda/5.0/developing-applications/api/application.html

**Comment by nadinequinr3** [comment]
> > > Preview here: https://docs.staging.docs.r3.com/en/platform/corda/5.0/developing-applications/api/application.html
> > 
> > 
> > Thanks @nadinequinr3 / @zhengmar3 I've tried it out and I don't get tooltips
> 
> @nadinequinr3 @yarivus Same for me, no tooltip.
> 
> Then I check the code from the Chrome inspect, my code change is not there. I think you (@nadinequinr3 ) might have setup the preview based on a wrong branch.

@zhengmar3 @yarivus My mistake - this is the correct site - https://corda5.preview.docs.r3.com/en/platform/corda/5.0/developing-applications/api/application.html

**Comment by yarivus** [comment]
> > > > Preview here: https://docs.staging.docs.r3.com/en/platform/corda/5.0/developing-applications/api/application.html
> > > 
> > > 
> > > Thanks @nadinequinr3 / @zhengmar3 I've tried it out and I don't get tooltips
> > 
> > 
> > @nadinequinr3 @yarivus Same for me, no tooltip.
> > Then I check the code from the Chrome inspect, my code change is not there. I think you (@nadinequinr3 ) might have setup the preview based on a wrong branch.
> 
> @zhengmar3 @yarivus My mistake - this is the correct site - https://corda5.preview.docs.r3.com/en/platform/corda/5.0/developing-applications/api/application.html

Works ;)

**Review by yarivus — APPROVED** [review]
LGTM

**Review by nadinequinr3 — APPROVED** [review]

**Pull request merged**
