### PR TITLE
F-71: Linked Heading with icon on hover

### PR DESCRIPTION
**Pull request by zhengmar3**
### Overview

Second try:

Added linked heading with icon on hover:
JIRA: https://r3-cev.atlassian.net/browse/FE-71

### Screenshot
image
image

### CODE REVIEW

**Review by colin-hillis — APPROVED** [review]
LGTM

**Comment by yarivus** [comment]
Hi @zhengmar3 ...I'm not sure I follow the change ... 
Can you paste a gif animation to understand how it behaves ?

**Comment by colin-hillis** [comment]
In this particular case, this is just trial and error to get round an issue that resolution has been tried for several times previously. This should have been marked as 'Don't review yet'.

**Comment by zhengmar3** [comment]
@yarivus 

https://github.com/corda/corda-docs-portal/assets/80267895/13e8bf52-0456-4e5a-8375-105d9f59d2e3

**Comment by yarivus** [comment]
thanks @zhengmar3

**Comment by colin-hillis** [comment]
Algolia has been reindexed now and it seems to be fine with the changes too. Good work @zhengmar3. Thanks

Uploading 2023-05-15_12-13-32.mp4…

**Comment by colin-hillis** [comment]
https://github.com/corda/corda-docs-portal/assets/112863914/8bb776fd-c92a-4334-8c3a-d236ccd37dba

**Pull request merged**
