### PR TITLE
FE-63: Table of contents highlight issue

### PR DESCRIPTION
**Pull request by zhengmar3**
### Overview

Issue: In most cases, when you click on the table of content, e.g. User click "Corda Package (CPKs)", the table of content will highlight "Cluster" section title. But user will probably expecting "Corda Package (CPKs)" to be highlighted.

Jira: https://r3-cev.atlassian.net/browse/FE-63

Screenshot 2023-02-24 at 12 26 36

_________________________

Current fix is to highlight clicked title and whatever is on the viewport of the user:

image

### CODE REVIEW

**Comment by colin-hillis** [comment]
Generating a preview of these changes to facilitate tech writer review. Thanks Zheng

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by colin-hillis** [comment]
> LGTM

@yarivus I haven't generated the preview yet.

**Comment by colin-hillis** [comment]
@zhengmar3 thanks for raising PR. Can you please check PR as the build. Once that is sorted, I can generate a preview site to facilitate reviews. TIA

**Comment by colin-hillis** [comment]
Preview site here: https://colin.preview.docs.r3.com/

**Review by colin-hillis — APPROVED** [review]
So much better Zheng. Thank you!

**Review by nadinequinr3 — APPROVED** [review]

**Comment by conor-r3** [comment]
> Preview site here: https://colin.preview.docs.r3.com/

There seems to be an issue with this preview. There is a gap between the red banner and the navigation bar. @zhengmar3 can you please check that you didn't inadvertently introduce a bug?

**Comment by conor-r3** [comment]
Screenshot 2023-02-27 at 12 09 57

**Comment by colin-hillis** [comment]
Hi Conor,

I built it on Anna’s preview site: HERE<https://anna.preview.docs.r3.com/>

My preview site was used to build an earlier iteration before Peter pushed a fix.

--
Colin Hillis
Lead Technical Writer | R3.
Remote | Northern Ireland
M:  (+44) 7830392955
***@***.******@***.***> | www.corda.net<http://www.corda.net/>

[signature_3478046804]
“The Power of 3”, only from R3: trust technology, connected networks, regulated markets expertise. Discover more at r3.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fr3.com%2F&data=05%7C01%7Ccolin.hillis%40r3.com%7C6bb5ffce2b0e40f4caa408da8b5f3607%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637975538291122586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fHDSUHQijWtlpEbevCome%2BGqPgX6coKLQ2nEr31FT2o%3D&reserved=0>.



From: Conor Pender ***@***.***>
Date: Monday, 27 February 2023 at 12:11
To: corda/corda-docs-portal ***@***.***>
Cc: Colin Hillis ***@***.***>, State change ***@***.***>
Subject: Re: [corda/corda-docs-portal] FE-63: Table of contents highlight issue (PR #1117)

[Screenshot 2023-02-27 at 12 09 57]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59569355%2F221560509-17a20591-0bc9-414f-80c6-ee9228552504.png&data=05%7C01%7Ccolin.hillis%40r3.com%7Cd4d0e002d96c499f6a6508db18bbb6dc%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130966737433832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RGHLGFFTLHI1epw7gjKLDyeKaDR2Z5zLnEObdLaRJCU%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcorda%2Fcorda-docs-portal%2Fpull%2F1117%23issuecomment-1446218998&data=05%7C01%7Ccolin.hillis%40r3.com%7Cd4d0e002d96c499f6a6508db18bbb6dc%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130966737433832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oXzLDfcWG4wNDY8VrvLJ0d113r4PQQV4nV%2FqoefhrGo%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA25CVKXVM6EBRNBJABBWKI3WZSKV5ANCNFSM6AAAAAAVG3DL7Y&data=05%7C01%7Ccolin.hillis%40r3.com%7Cd4d0e002d96c499f6a6508db18bbb6dc%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130966737433832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T2hvv0sfKTtF59%2F7Jmn043s%2BEYpe0OPfTB%2FmOmw2CYE%3D&reserved=0>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

R3 is committed to ensuring the security and protection of the personal data that we process, and to provide a compliant and consistent approach to data protection. Any personal data that is shared as part of any email correspondence with R3 shall be processed in line with the R3 Privacy Policy<https://www.r3.com/full-privacy-policy/>

**Comment by colin-hillis** [comment]
Actually Conor…you are right. The banner looks OK on the homepage, but when you drill into doc pages, it changes to introduce a space, like you said. Good catch Conor!

--
Colin Hillis
Lead Technical Writer | R3.
Remote | Northern Ireland
M:  (+44) 7830392955
***@***.******@***.***> | www.corda.net<http://www.corda.net/>

[signature_3478046804]
“The Power of 3”, only from R3: trust technology, connected networks, regulated markets expertise. Discover more at r3.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fr3.com%2F&data=05%7C01%7Ccolin.hillis%40r3.com%7C6bb5ffce2b0e40f4caa408da8b5f3607%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637975538291122586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fHDSUHQijWtlpEbevCome%2BGqPgX6coKLQ2nEr31FT2o%3D&reserved=0>.



From: Colin Hillis ***@***.***>
Date: Monday, 27 February 2023 at 12:25
To: corda/corda-docs-portal ***@***.***>, corda/corda-docs-portal ***@***.***>
Cc: State change ***@***.***>
Subject: Re: [corda/corda-docs-portal] FE-63: Table of contents highlight issue (PR #1117)
Hi Conor,

I built it on Anna’s preview site: HERE<https://anna.preview.docs.r3.com/>

My preview site was used to build an earlier iteration before Peter pushed a fix.

--
Colin Hillis
Lead Technical Writer | R3.
Remote | Northern Ireland
M:  (+44) 7830392955
***@***.******@***.***> | www.corda.net<http://www.corda.net/>

[signature_3478046804]
“The Power of 3”, only from R3: trust technology, connected networks, regulated markets expertise. Discover more at r3.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fr3.com%2F&data=05%7C01%7Ccolin.hillis%40r3.com%7C6bb5ffce2b0e40f4caa408da8b5f3607%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637975538291122586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fHDSUHQijWtlpEbevCome%2BGqPgX6coKLQ2nEr31FT2o%3D&reserved=0>.



From: Conor Pender ***@***.***>
Date: Monday, 27 February 2023 at 12:11
To: corda/corda-docs-portal ***@***.***>
Cc: Colin Hillis ***@***.***>, State change ***@***.***>
Subject: Re: [corda/corda-docs-portal] FE-63: Table of contents highlight issue (PR #1117)

[Screenshot 2023-02-27 at 12 09 57]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F59569355%2F221560509-17a20591-0bc9-414f-80c6-ee9228552504.png&data=05%7C01%7Ccolin.hillis%40r3.com%7Cd4d0e002d96c499f6a6508db18bbb6dc%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130966737433832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RGHLGFFTLHI1epw7gjKLDyeKaDR2Z5zLnEObdLaRJCU%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcorda%2Fcorda-docs-portal%2Fpull%2F1117%23issuecomment-1446218998&data=05%7C01%7Ccolin.hillis%40r3.com%7Cd4d0e002d96c499f6a6508db18bbb6dc%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130966737433832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oXzLDfcWG4wNDY8VrvLJ0d113r4PQQV4nV%2FqoefhrGo%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA25CVKXVM6EBRNBJABBWKI3WZSKV5ANCNFSM6AAAAAAVG3DL7Y&data=05%7C01%7Ccolin.hillis%40r3.com%7Cd4d0e002d96c499f6a6508db18bbb6dc%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130966737433832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=T2hvv0sfKTtF59%2F7Jmn043s%2BEYpe0OPfTB%2FmOmw2CYE%3D&reserved=0>.
You are receiving this because you modified the open/close state.Message ID: ***@***.***>

R3 is committed to ensuring the security and protection of the personal data that we process, and to provide a compliant and consistent approach to data protection. Any personal data that is shared as part of any email correspondence with R3 shall be processed in line with the R3 Privacy Policy<https://www.r3.com/full-privacy-policy/>

**Comment by zhengmar3** [comment]
@colin-hillis  @conor-r3 
Current live version of docs site works fine. And it got all my latest changes. 
It's very unlikely caused by this PR.

image

**Comment by colin-hillis** [comment]
Potentially Peter’s PR regarding the banner

--
Colin Hillis
Lead Technical Writer | R3.
Remote | Northern Ireland
M:  (+44) 7830392955
***@***.******@***.***> | www.corda.net<http://www.corda.net/>

[signature_3478046804]
“The Power of 3”, only from R3: trust technology, connected networks, regulated markets expertise. Discover more at r3.com<https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fr3.com%2F&data=05%7C01%7Ccolin.hillis%40r3.com%7C6bb5ffce2b0e40f4caa408da8b5f3607%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C637975538291122586%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fHDSUHQijWtlpEbevCome%2BGqPgX6coKLQ2nEr31FT2o%3D&reserved=0>.



From: Zheng Ma ***@***.***>
Date: Monday, 27 February 2023 at 12:32
To: corda/corda-docs-portal ***@***.***>
Cc: Colin Hillis ***@***.***>, Mention ***@***.***>
Subject: Re: [corda/corda-docs-portal] FE-63: Table of contents highlight issue (PR #1117)

@colin-hillis<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcolin-hillis&data=05%7C01%7Ccolin.hillis%40r3.com%7C670ba811ead94ca0126608db18bec022%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130979777365058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=O8FdbwcfBJEHibBjMpuR0kkhMWk%2BBts9wJXYmvCIR3U%3D&reserved=0> @conor-r3<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fconor-r3&data=05%7C01%7Ccolin.hillis%40r3.com%7C670ba811ead94ca0126608db18bec022%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130979777365058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FqCFigHEzpo3ZeSLzxRIzip2OZvHwR9gTYsuasuLQ58%3D&reserved=0>
Current live version of docs site works fine. And it got all my latest changes.
It's very unlikely caused by this PR.

[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F80267895%2F221564393-e29e71e0-95c4-404b-bb4b-ad1716fa0e48.png&data=05%7C01%7Ccolin.hillis%40r3.com%7C670ba811ead94ca0126608db18bec022%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130979777365058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KZHAJAniJxvzB1EFG1JSWOCM9V7A4FMD342xk0Ol0gM%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcorda%2Fcorda-docs-portal%2Fpull%2F1117%23issuecomment-1446250024&data=05%7C01%7Ccolin.hillis%40r3.com%7C670ba811ead94ca0126608db18bec022%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130979777365058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=javwJ8qy%2Bk%2FaX8%2BG55%2FD7%2FtA6FRKlIoc99IKC%2Fi1qk4%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA25CVKWNABUWDSLRMQWTLLTWZSNHNANCNFSM6AAAAAAVG3DL7Y&data=05%7C01%7Ccolin.hillis%40r3.com%7C670ba811ead94ca0126608db18bec022%7Ca4be1f2e2d10419587cd736aca9b672c%7C0%7C0%7C638130979777521256%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ad8d%2BeApc4G5%2F4c6qqYquJ5Cg9TV9VKclpavHuoJ11E%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

R3 is committed to ensuring the security and protection of the personal data that we process, and to provide a compliant and consistent approach to data protection. Any personal data that is shared as part of any email correspondence with R3 shall be processed in line with the R3 Privacy Policy<https://www.r3.com/full-privacy-policy/>

**Pull request merged**
