### PR TITLE
DOC-5624: Removed mentions of SSO from C5 GA docs

### PR DESCRIPTION
**Pull request by AnnaK-R3**

### CODE REVIEW

**Review by vkolomeyko — APPROVED** [review]
LGTM

**Review by driessamyn — APPROVED** [review]
LGTM

**Review by amiegrace12 — APPROVED** [review]

**Review by colin-hillis — APPROVED** [review]
LGTM - Thanks Anna

**Review by yarivus — APPROVED** [review]
LGTM

**Pull request merged**
